=== bdombrow/CS-510-NiagaraST-Last-Known-Good/demo/data/league.dtd
<!ELEMENT PNAME (#PCDATA)>
<!ELEMENT PLRID (#PCDATA)>
<!ELEMENT STDATE (#PCDATA)>
<!ELEMENT ENDDATE (#PCDATA)>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT POSITION (#PCDATA)>
<!ELEMENT RESERVE (#PCDATA)>

<!ELEMENT LEAGUESYSTEM (LEAGUE+)>
   <!ELEMENT LEAGUE (TEAM+)>
      <!ELEMENT TEAM (NAME, ROSTER)>
         <!ELEMENT ROSTER (PLAYER+)>
            <!ELEMENT PLAYER (PNAME, PLRID, (POSITION | RESERVE), STDATE, ENDDATE)>

=== bdombrow/CS-510-NiagaraST-Last-Known-Good/demo/data/PetesLeague.xml
<?xml version = "1.0"?>
<!DOCTYPE LEAGUESYSTEM SYSTEM "league.dtd">
<LEAGUESYSTEM>
<LEAGUE>
	<TEAM>
		<NAME> Chen's Chiefs </NAME>
		<ROSTER>
			<PLAYER>
				<PNAME> "Lou Thornton" </PNAME>
				<PLRID> thorl001 </PLRID>
				<POSITION> P  </POSITION>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Eric Show" </PNAME>
				<PLRID> showe001 </PLRID>
				<POSITION> P  </POSITION>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Mickey Hatcher" </PNAME>
				<PLRID> hatcm001 </PLRID>
				<POSITION> P  </POSITION>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Todd Burns" </PNAME>
				<PLRID> burnt001 </PLRID>
				<POSITION> P  </POSITION>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Rick Honeycutt" </PNAME>
				<PLRID> honer001 </PLRID>
				<POSITION> P  </POSITION>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Franklin Stubbs" </PNAME>
				<PLRID> stubf001 </PLRID>
				<POSITION> P  </POSITION>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Gene Petralli" </PNAME>
				<PLRID> petrg001 </PLRID>
				<POSITION> P  </POSITION>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Tom Henke" </PNAME>
				<PLRID> henkt001 </PLRID>
				<POSITION> P  </POSITION>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Daryl Boston" </PNAME>
				<PLRID> bostd001 </PLRID>
				<POSITION> P  </POSITION>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Wally Backman" </PNAME>
				<PLRID> backw001 </PLRID>
				<POSITION> C  </POSITION>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Steve Balboni" </PNAME>
				<PLRID> balbs001 </PLRID>
				<POSITION> C  </POSITION>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Mike Laga" </PNAME>
				<PLRID> lagam001 </PLRID>
				<POSITION> 1B </POSITION>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Pete O'Brien" </PNAME>
				<PLRID> obrip001 </PLRID>
				<POSITION> 1B </POSITION>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Luis Quinones" </PNAME>
				<PLRID> quinl001 </PLRID>
				<POSITION> 2B </POSITION>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Gus Polidor" </PNAME>
				<PLRID> polig001 </PLRID>
				<POSITION> 3B </POSITION>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Fred Manrique" </PNAME>
				<PLRID> manrf001 </PLRID>
				<POSITION> SS </POSITION>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Barry Larkin" </PNAME>
				<PLRID> larkb001 </PLRID>
				<POSITION> SS </POSITION>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Vince Coleman" </PNAME>
				<PLRID> colev001 </PLRID>
				<POSITION> LF </POSITION>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Bob Dernier" </PNAME>
				<PLRID> dernb001 </PLRID>
				<POSITION> LF </POSITION>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Tommy Gregg" </PNAME>
				<PLRID> gregt001 </PLRID>
				<POSITION> CF </POSITION>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "John Shelby" </PNAME>
				<PLRID> shelj001 </PLRID>
				<POSITION> CF </POSITION>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Dave Clark" </PNAME>
				<PLRID> clard001 </PLRID>
				<POSITION> RF </POSITION>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Jeff Leonard" </PNAME>
				<PLRID> leonj001 </PLRID>
				<POSITION> DH </POSITION>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Buddy Bell" </PNAME>
				<PLRID> bellb001 </PLRID>
				<RESERVE/>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Bill Buckner" </PNAME>
				<PLRID> buckb001 </PLRID>
				<RESERVE/>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Sam Horn" </PNAME>
				<PLRID> horns001 </PLRID>
				<RESERVE/>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Bill Spiers" </PNAME>
				<PLRID> spieb001 </PLRID>
				<RESERVE/>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "? Shaefer" </PNAME>
				<PLRID> shead001 </PLRID>
				<RESERVE/>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Cecil Espy" </PNAME>
				<PLRID> espyc001 </PLRID>
				<RESERVE/>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Jerry Browne" </PNAME>
				<PLRID> browj001 </PLRID>
				<RESERVE/>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Glenallen Hill" </PNAME>
				<PLRID> hillg001 </PLRID>
				<RESERVE/>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Jim Acker" </PNAME>
				<PLRID> ackej001 </PLRID>
				<RESERVE/>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Jeff Treadway" </PNAME>
				<PLRID> treaj001 </PLRID>
				<RESERVE/>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Wallace Johnson" </PNAME>
				<PLRID> johnw001 </PLRID>
				<RESERVE/>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Pete Smith" </PNAME>
				<PLRID> smitp001 </PLRID>
				<RESERVE/>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Chuck Finley" </PNAME>
				<PLRID> finlc001 </PLRID>
				<RESERVE/>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Pat Perry" </PNAME>
				<PLRID> perrp001 </PLRID>
				<RESERVE/>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Mike Davis" </PNAME>
				<PLRID> davim002 </PLRID>
				<RESERVE/>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Greg Gross" </PNAME>
				<PLRID> grosg001 </PLRID>
				<RESERVE/>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Jeff Robinson" </PNAME>
				<PLRID> robij002 </PLRID>
				<RESERVE/>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Lee Guetterman" </PNAME>
				<PLRID> guetl001 </PLRID>
				<RESERVE/>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Gary Varsho" </PNAME>
				<PLRID> varsg001 </PLRID>
				<RESERVE/>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Cecilio Guante" </PNAME>
				<PLRID> guanc001 </PLRID>
				<RESERVE/>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Erik Hanson" </PNAME>
				<PLRID> hanse001 </PLRID>
				<RESERVE/>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Doyle Alexander" </PNAME>
				<PLRID> alexd001 </PLRID>
				<RESERVE/>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Barry Jones" </PNAME>
				<PLRID> joneb002 </PLRID>
				<RESERVE/>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Glenn Wilson" </PNAME>
				<PLRID> wilsg001 </PLRID>
				<RESERVE/>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Jim Abbott" </PNAME>
				<PLRID> abboj001 </PLRID>
				<RESERVE/>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Otis Nixon" </PNAME>
				<PLRID> nixoo001 </PLRID>
				<RESERVE/>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Kevin Brown" </PNAME>
				<PLRID> browk001 </PLRID>
				<RESERVE/>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Erik Yelding" </PNAME>
				<PLRID> yelde001 </PLRID>
				<RESERVE/>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Tom Pagnozzi" </PNAME>
				<PLRID> pagnt001 </PLRID>
				<RESERVE/>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Mark Parent" </PNAME>
				<PLRID> parem001 </PLRID>
				<RESERVE/>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Charlie Puleo" </PNAME>
				<PLRID> pulec001 </PLRID>
				<RESERVE/>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Ken Hill" </PNAME>
				<PLRID> hillk001 </PLRID>
				<RESERVE/>
				<STDATE> 04/01/89 </STDATE>
				<ENDDATE> 10/03/89 </ENDDATE>
			</PLAYER>
			<PLAYER>
				<PNAME> "Bill Swift" </PNAME>
				<PLRID> swifb001 </PLRID>
